#!/bin/bash

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  🔧 QUICK FIX: Copy Correct Filter to Clipboard              ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "When the annotation opens Datadog with WRONG filter:"
echo ""
echo "❌ Wrong: service:(eran-njs)"
echo "✅ Correct: service:datadog-demo-app"
echo ""
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "COPY THIS FILTER:"
echo ""
echo "service:datadog-demo-app message:\"Homepage accessed\""
echo ""
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "📋 QUICK STEPS:"
echo "1. Click the annotation in Cursor"
echo "2. When Datadog opens, click the search bar"
echo "3. Delete the old filter (Cmd+A, Delete)"
echo "4. Paste the correct filter above"
echo "5. Press Enter"
echo "6. ✅ See all 101 logs!"
echo ""
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "📎 OTHER USEFUL FILTERS:"
echo ""
echo "All logs:"
echo "  service:datadog-demo-app"
echo ""
echo "Users API:"
echo "  service:datadog-demo-app message:\"Fetching all users\""
echo ""
echo "Orders API:"
echo "  service:datadog-demo-app message:\"Fetching all orders\""
echo ""
echo "Health checks:"
echo "  service:datadog-demo-app message:\"Health check performed\""
echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  🌐 DIRECT LINKS (Bookmark These)                            ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "All logs:"
echo "https://app.datadoghq.com/logs?query=service%3Adatadog-demo-app"
echo ""
echo "Homepage logs:"
echo "https://app.datadoghq.com/logs?query=service%3Adatadog-demo-app%20message%3A%22Homepage%20accessed%22"
echo ""
